//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class звонки
    {
        public звонки()
        {
            this.прим = "";
            this.код_сообщения = "";
            this.телефон = "";
            this.доставка = "";
            this.статус = "";
            this.доставлено = false;
        }
    
        public System.Guid звонок { get; set; }
        public System.Guid клиент { get; set; }
        public System.DateTime дата { get; set; }
        public System.Guid услуга { get; set; }
        public string прим { get; set; }
        public string код_сообщения { get; set; }
        public string телефон { get; set; }
        public string доставка { get; set; }
        public string статус { get; set; }
        public bool доставлено { get; set; }
    
        public virtual клиенты клиенты { get; set; }
        public virtual услуги услуги { get; set; }
    }
}
