//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class поселки
    {
        public поселки()
        {
            this.улицы = new HashSet<улицы>();
        }
    
        public System.Guid поселок { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
        public int улиц
        {
            get { return улицы.Count; }
        }
    
        public virtual ICollection<улицы> улицы { get; set; }
    }
}
