//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class сотрудники
    {
        public сотрудники()
        {
            this.опл_работы = new HashSet<опл_работы>();
            this.оплаты = new HashSet<оплаты>();
            this.отключения = new HashSet<отключения>();
            this.повторы = new HashSet<повторы>();
            this.подключения = new HashSet<подключения>();
        }
    
        public System.Guid сотрудник { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public int порядок { get; set; }
        public string прим { get; set; }
        public string адрес { get; set; }
        public string телефон { get; set; }
        public string фото { get; set; }
        public Nullable<System.DateTime> дата_рож { get; set; }
        public string фио { get; set; }
        public Nullable<System.DateTime> принят { get; set; }
        public Nullable<System.DateTime> уволен { get; set; }
        public string должность { get; set; }
        public bool кассир { get; set; }

        public override string ToString()
        {
            return фио ;
        }
        public virtual ICollection<опл_работы> опл_работы { get; set; }
        public virtual ICollection<оплаты> оплаты { get; set; }
        public virtual ICollection<отключения> отключения { get; set; }
        public virtual ICollection<повторы> повторы { get; set; }
        public virtual ICollection<подключения> подключения { get; set; }
    }
}
