//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class фирмы
    {
        public System.Guid фирма { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
        public string название { get; set; }
        public string адрес { get; set; }
        public string факт_адрес { get; set; }
        public string телефон { get; set; }
        public string р_счет { get; set; }
        public string к_счет { get; set; }
        public string банк { get; set; }
        public string город { get; set; }
        public string бик { get; set; }
        public string код { get; set; }
        public string инн { get; set; }
        public string окпо { get; set; }
        public string оконх { get; set; }
        public string груз_пол { get; set; }
    }
}
