<?xml version="1.0" encoding="utf-8"?><Database Name="domofon14" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=user14;Initial Catalog=domofon14;User ID=sa" SettingsObjectName="domofon40.Properties.Settings" SettingsPropertyName="domofon14ConnectionString" Provider="System.Data.SqlClient" />
</Database>