//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class del_оплачено
    {
        public int код { get; set; }
        public System.Guid оплата { get; set; }
        public int месяц { get; set; }
        public int год { get; set; }
        public int сумма { get; set; }
        public System.Guid услуга { get; set; }
        public System.DateTime дата { get; set; }
    }
}
