//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class виды_оплат
    {
        public виды_оплат()
        {
            this.оплаты = new HashSet<оплаты>();
        }
    
        public System.Guid вид_оплаты { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
    
        public virtual ICollection<оплаты> оплаты { get; set; }
    }
}
