//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class дома
    {
        public дома()
        {
            this.клиенты = new HashSet<клиенты>();
        }
    
        public System.Guid дом { get; set; }
        public System.Guid улица { get; set; }
        public int номер { get; set; }
        public string корпус { get; set; }
        public System.DateTime изменен { get; set; }
    
        public virtual улицы улицы { get; set; }
        public virtual ICollection<клиенты> клиенты { get; set; }
    }
}
