//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class клиенты
    {
        public клиенты()
        {
            this.оплаты = new HashSet<оплаты>();
            this.отключения = new HashSet<отключения>();
            this.повторы = new HashSet<повторы>();
            this.подключения = new HashSet<подключения>();
            this.примечания = new HashSet<примечания>();
            this.раб_дней = new HashSet<раб_дней>();
            this.услуги = new HashSet<услуги>();
            this.звонки = new HashSet<звонки>();
            this.простои = new HashSet<простои>();
            this.льготы = new HashSet<льготы>();
        }
    
        public System.Guid клиент { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public System.Guid дом { get; set; }
        public int квартира { get; set; }
        public string фио { get; set; }
        public string прим { get; set; }
        public int подъезд { get; set; }
        public string телефон { get; set; }
        public int ввод { get; set; }
    
        public virtual ICollection<оплаты> оплаты { get; set; }
        public virtual ICollection<отключения> отключения { get; set; }
        public virtual ICollection<повторы> повторы { get; set; }
        public virtual ICollection<подключения> подключения { get; set; }
        public virtual ICollection<примечания> примечания { get; set; }
        public virtual ICollection<раб_дней> раб_дней { get; set; }
        public virtual ICollection<услуги> услуги { get; set; }
        public virtual ICollection<звонки> звонки { get; set; }
        public virtual ICollection<простои> простои { get; set; }
        public virtual дома дома { get; set; }
        public virtual ICollection<льготы> льготы { get; set; }
    }
}
