//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class оплаты
    {
        public оплаты()
        {
            this.опл_работы = new HashSet<опл_работы>();
            this.возврат = new HashSet<возврат>();
            this.воз_работы = new HashSet<воз_работы>();
            this.оплачено = new HashSet<оплачено>();
        }
    
        public System.Guid оплата { get; set; }
        public int номер { get; set; }
        public System.Guid клиент { get; set; }
        public System.DateTime дата { get; set; }
        public System.Guid сотрудник { get; set; }
        public System.Guid вид_оплаты { get; set; }
    
        public virtual клиенты клиенты { get; set; }
        public virtual ICollection<опл_работы> опл_работы { get; set; }
        public virtual ICollection<возврат> возврат { get; set; }
        public virtual сотрудники сотрудники { get; set; }
        public virtual виды_оплат виды_оплат { get; set; }
        public virtual ICollection<воз_работы> воз_работы { get; set; }
        public virtual ICollection<оплачено> оплачено { get; set; }
    }
}
