//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class работы
    {
        public работы()
        {
            this.опл_работы = new HashSet<опл_работы>();
            this.воз_работы = new HashSet<воз_работы>();
        }
    
        public System.Guid работа { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
        public int стоимость { get; set; }
        public int ст_материалов { get; set; }
        public string прейскурант { get; set; }
    
        public virtual ICollection<опл_работы> опл_работы { get; set; }
        public virtual ICollection<воз_работы> воз_работы { get; set; }
    }
}
