//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class разрешения
    {
        public System.Guid разрешение { get; set; }
        public System.Guid клиент { get; set; }
        public System.DateTime дата_с { get; set; }
        public int номер { get; set; }
        public Nullable<System.DateTime> дата_по { get; set; }
        public string телефон { get; set; }
        public string эл_почта { get; set; }
    
        public virtual клиенты клиенты { get; set; }
    }
}
