//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class услуги
    {
        public услуги()
        {
            this.отключения = new HashSet<отключения>();
            this.повторы = new HashSet<повторы>();
            this.подключения = new HashSet<подключения>();
            this.примечания = new HashSet<примечания>();
            this.раб_дней = new HashSet<раб_дней>();
            this.цены = new HashSet<цены>();
            this.клиенты = new HashSet<клиенты>();
            this.простои = new HashSet<простои>();
            this.возврат = new HashSet<возврат>();
            this.льготы = new HashSet<льготы>();
            this.оплачено = new HashSet<оплачено>();
        }
    
        public System.Guid услуга { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
        public System.Guid вид_услуги { get; set; }
        public string обозначение { get; set; }
    
        public virtual виды_услуг виды_услуг { get; set; }
        public virtual ICollection<отключения> отключения { get; set; }
        public virtual ICollection<повторы> повторы { get; set; }
        public virtual ICollection<подключения> подключения { get; set; }
        public virtual ICollection<примечания> примечания { get; set; }
        public virtual ICollection<раб_дней> раб_дней { get; set; }
        public virtual ICollection<цены> цены { get; set; }
        public virtual ICollection<клиенты> клиенты { get; set; }
        public virtual ICollection<простои> простои { get; set; }
        public virtual ICollection<возврат> возврат { get; set; }
        public virtual ICollection<льготы> льготы { get; set; }
        public virtual ICollection<оплачено> оплачено { get; set; }
    }
}
