//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domofon40
{
    using System;
    using System.Collections.Generic;
    
    public partial class филиалы
    {
        public System.Guid филиал { get; set; }
        public string наимен { get; set; }
        public string адрес { get; set; }
        public int порядок { get; set; }
        public string телефон { get; set; }
    }
}
